=== bryanhughes1992/PHP-XML-DOM/supportTicket.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="supportTicket">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ticketNumber" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:int"/>
              <xs:element name="subject" type="xs:string" />
              <xs:element name="startdate" type="xs:dateTime" />
              <xs:element name="enddate" type="xs:dateTime"/>
              <xs:element name="partsRequired" type="xs:boolean"/>
              <xs:element name="resolved" type="xs:boolean"></xs:element>
              <xs:element name="message" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="userId" type="xs:int"/>
                      <xs:attribute name="dateSent" type="xs:dateTime"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bryanhughes1992/PHP-XML-DOM/xml/supportTicket.xml
<?xml version="1.0" encoding="UTF-8"?>
<supportTicket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./supportTicket.xsd">
  <ticketNumber>
    <id>0001</id>
    <subject>Computer Problems</subject>
    <startdate>2021-02-23T04:20:00</startdate>
    <enddate>2021-02-23T04:25:03</enddate>
    <partsRequired>false</partsRequired>
    <resolved>true</resolved>
    <message userId="0002" dateSent="2021-02-23T04:20:00">Hello</message>
  </ticketNumber>
  <ticketNumber>
    <id>0002</id>
    <subject>Broken Printer</subject>
    <startdate>2021-01-02T08:30:00</startdate>
    <enddate>2021-01-02T23:59:59</enddate>
    <partsRequired>true</partsRequired>
    <resolved>false</resolved>
    <message userId="0001" dateSent="2021-01-02T09:22:00">I slopped PBandJ on the printer</message>
    <message userId="0007" dateSent="2021-01-02T12:33:00">We're going to have to get a new printer</message>
  </ticketNumber>
  <ticketNumber>
    <id>0003</id>
    <subject>Corrupt Disk Drive</subject>
    <startdate>2021-02-02T16:30:48</startdate>
    <enddate>2021-02-22T12:20:20</enddate>
    <partsRequired>true</partsRequired>
    <resolved>true</resolved>
    <message userId="0020" dateSent="2021-02-22T12:20:00">Hi Jessica, your computer is now working.</message>
  </ticketNumber>
</supportTicket>
